# Generated by Django 3.1.1 on 2020-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20201228_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, default='product.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img4',
            field=models.ImageField(blank=True, default='product.png', null=True, upload_to=''),
        ),
    ]
