# Generated by Django 3.1.1 on 2021-01-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_auto_20201229_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
