# Generated by Django 3.1.1 on 2021-01-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
