# Generated by Django 3.1.1 on 2021-01-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_auto_20210105_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_created',
        ),
    ]
