# Generated by Django 3.1.1 on 2021-01-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0021_auto_20210105_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
