# Generated by Django 3.1.1 on 2021-01-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0025_auto_20210107_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
