# Generated by Django 3.1.1 on 2021-01-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0026_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
