# Generated by Django 3.1.1 on 2021-01-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0029_remove_contact_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('US7', 'US7'), ('US7.5', 'US7.5'), ('US8', 'US8'), ('US8.5', 'US8.5'), ('US9', 'US9'), ('US9.5', 'US9.5'), ('US10', 'US10'), ('US10.5', 'US10.5')], default='US8', max_length=200),
        ),
    ]
