# Generated by Django 3.1.1 on 2021-01-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0030_auto_20210118_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
