# Generated by Django 3.1.1 on 2021-01-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0031_auto_20210120_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, default='product.png', null=True, upload_to=''),
        ),
    ]
