# Generated by Django 3.1.1 on 2021-01-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0032_auto_20210120_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img5',
            field=models.ImageField(blank=True, default='product.png', null=True, upload_to=''),
        ),
    ]
