# Generated by Django 3.1.1 on 2021-01-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0033_product_product_img5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img5',
        ),
    ]
