# Generated by Django 3.1.1 on 2021-01-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
