# Generated by Django 3.1.1 on 2021-01-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
