# Generated by Django 3.1.1 on 2021-02-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0036_product_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='positiive',
            field=models.BooleanField(default=False),
        ),
    ]
